### ISSUE TITLE
Easier to add tags

### ISSUE THREAD

**Issue by Angels-D** [Curvu/ayu-friends-plus#20]
One way to do this is to add a column to the shortcut list that contains all of your tagged friends. We can add friends to this big collection and tag them first, which is much more convenient than finding and tagging them from all of our friends.
Then, I tried to add an input box and use the keyboard input to find friends, but every time I typed the keyboard, I would exit the friends window, and I didn't know much about Adobe Flash development, so was this possible?

**Comment by Curvu** [comment]
The keyboard input is not possible sadly, because trove blocked that interface... that's why i did a digital keyboard, Sadly.
and wdym about the tagged friends?

**Comment by Angels-D** [comment]
> The keyboard input is not possible sadly, because trove blocked that interface... that's why i did a digital keyboard, Sadly.

I think so.
> the tagged friends

For example, I added tags to the Favorites section so that I could tag them from a more streamlined list of friends.
I think it would be useful to have a rainbow tag that could include any other color tag.

**Comment by Curvu** [comment]
you have so many colors you dont need and you can use that color to do it... i dont think that "feature" would be usefull, unless you draw a scatch so i can understand your idea better
